version: '3.3'
services:

  secret-room-landing:
    container_name: secret-room-landing
    image: zakella/secret-room-landing:latest
    ports:
      - "6200:80"
    restart: unless-stopped

networks:
  secret-room-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

volumes:
  gmail_tokens:
