
  name: CD - Deploy Frontend

  on:
    push:
      branches:
        - master
      paths:
        - '**'

  jobs:
    deploy:
      runs-on: ubuntu-latest


      steps:
#        - uses: actions/checkout@v3
#
#        - name: Set up Node.js
#          uses: actions/setup-node@v3
#          with:
#            node-version: '20'
#
#        - name: Install npm dependencies
#          run: npm install
#
#        - name: Build Angular project
#          run: npm run build -- --configuration production
#
#        - name: Login to Docker Hub
#          uses: docker/login-action@v2
#          with:
#            username: ${{ secrets.DOCKERHUB_USERNAME }}
#            password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
#
#        - name: Build and push Docker image
#          run: |
#            docker build -t zakella/secret-room-landing:${{ github.sha }} .
#            docker push zakella/secret-room-landing:${{ github.sha }}
#            docker tag zakella/secret-room-landing:${{ github.sha }} zakella/secret-room-landing:latest
#            docker push zakella/secret-room-landing:latest

        - name: Deploying application to server
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.SHH_PRIVATE_KEY }}
            script: |
              cd ~/secret-room-landing/SecretRoomLandingPage
              git pull
              docker-compose pull secret-room-landing
              docker-compose down
              docker-compose up -d

